/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetsRouteImport } from './routes/widgets'
import { Route as WidgetCustomizeRouteImport } from './routes/widget-customize'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReflectRouteImport } from './routes/reflect'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HardcoreRouteImport } from './routes/hardcore'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AndroidReadinessRouteImport } from './routes/android-readiness'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const WidgetsRoute = WidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetCustomizeRoute = WidgetCustomizeRouteImport.update({
  id: '/widget-customize',
  path: '/widget-customize',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectRoute = ReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HardcoreRoute = HardcoreRouteImport.update({
  id: '/hardcore',
  path: '/hardcore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AndroidReadinessRoute = AndroidReadinessRouteImport.update({
  id: '/android-readiness',
  path: '/android-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/android-readiness': typeof AndroidReadinessRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/hardcore': typeof HardcoreRoute
  '/insights': typeof InsightsRoute
  '/journey': typeof JourneyRoute
  '/milestones': typeof MilestonesRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recovery': typeof RecoveryRoute
  '/reflect': typeof ReflectRoute
  '/settings': typeof SettingsRoute
  '/widget-customize': typeof WidgetCustomizeRoute
  '/widgets': typeof WidgetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/android-readiness': typeof AndroidReadinessRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/hardcore': typeof HardcoreRoute
  '/insights': typeof InsightsRoute
  '/journey': typeof JourneyRoute
  '/milestones': typeof MilestonesRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recovery': typeof RecoveryRoute
  '/reflect': typeof ReflectRoute
  '/settings': typeof SettingsRoute
  '/widget-customize': typeof WidgetCustomizeRoute
  '/widgets': typeof WidgetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/android-readiness': typeof AndroidReadinessRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/hardcore': typeof HardcoreRoute
  '/insights': typeof InsightsRoute
  '/journey': typeof JourneyRoute
  '/milestones': typeof MilestonesRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recovery': typeof RecoveryRoute
  '/reflect': typeof ReflectRoute
  '/settings': typeof SettingsRoute
  '/widget-customize': typeof WidgetCustomizeRoute
  '/widgets': typeof WidgetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/android-readiness'
    | '/app'
    | '/auth'
    | '/hardcore'
    | '/insights'
    | '/journey'
    | '/milestones'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/recovery'
    | '/reflect'
    | '/settings'
    | '/widget-customize'
    | '/widgets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/android-readiness'
    | '/app'
    | '/auth'
    | '/hardcore'
    | '/insights'
    | '/journey'
    | '/milestones'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/recovery'
    | '/reflect'
    | '/settings'
    | '/widget-customize'
    | '/widgets'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/android-readiness'
    | '/app'
    | '/auth'
    | '/hardcore'
    | '/insights'
    | '/journey'
    | '/milestones'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/recovery'
    | '/reflect'
    | '/settings'
    | '/widget-customize'
    | '/widgets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AndroidReadinessRoute: typeof AndroidReadinessRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  HardcoreRoute: typeof HardcoreRoute
  InsightsRoute: typeof InsightsRoute
  JourneyRoute: typeof JourneyRoute
  MilestonesRoute: typeof MilestonesRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RecoveryRoute: typeof RecoveryRoute
  ReflectRoute: typeof ReflectRoute
  SettingsRoute: typeof SettingsRoute
  WidgetCustomizeRoute: typeof WidgetCustomizeRoute
  WidgetsRoute: typeof WidgetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widgets': {
      id: '/widgets'
      path: '/widgets'
      fullPath: '/widgets'
      preLoaderRoute: typeof WidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget-customize': {
      id: '/widget-customize'
      path: '/widget-customize'
      fullPath: '/widget-customize'
      preLoaderRoute: typeof WidgetCustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflect': {
      id: '/reflect'
      path: '/reflect'
      fullPath: '/reflect'
      preLoaderRoute: typeof ReflectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardcore': {
      id: '/hardcore'
      path: '/hardcore'
      fullPath: '/hardcore'
      preLoaderRoute: typeof HardcoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/android-readiness': {
      id: '/android-readiness'
      path: '/android-readiness'
      fullPath: '/android-readiness'
      preLoaderRoute: typeof AndroidReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AndroidReadinessRoute: AndroidReadinessRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  HardcoreRoute: HardcoreRoute,
  InsightsRoute: InsightsRoute,
  JourneyRoute: JourneyRoute,
  MilestonesRoute: MilestonesRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RecoveryRoute: RecoveryRoute,
  ReflectRoute: ReflectRoute,
  SettingsRoute: SettingsRoute,
  WidgetCustomizeRoute: WidgetCustomizeRoute,
  WidgetsRoute: WidgetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
